### PR TITLE
Add Pocophone F1 hildon-meta package

### PR DESCRIPTION
**Pull request by Venji10**

### CODE REVIEW

**Comment by IMbackK** [comment]
NAK, this should not conflict xserver-xorg-input-libinput, instead the ts of the f1 should be configured to use the xorg evdev xinput driver. 

simply conflicting xserver-xorg-input-libinput to stop it being used for the ts removes it entirely, also for other input devices that might be connected via otg

**Comment by Venji10** [comment]
@IMbackK why does every other meta package conflict with xserver-xorg-input-libinput then? Also, we don't even have OTG working on that device yet.

**Comment by IMbackK** [comment]
@Venji10 same invalid reason, @parazyd. 
the "Driver" option should be used in xorg conf to select evdev

**Comment by parazyd** [comment]
> @Venji10 same invalid reason, @parazyd.
> the "Driver" option should be used in xorg conf to select evdev

Feel free to open another ticket for this and potentially fix it. Thanks.
We are banning libinput from the beginning because it hadn't worked with the N900 TS, and IIRC even the droid4 had issue.

We were also unable to do proper ts calibration with libinput as there is no actual tool we're aware of that can do it.

**Comment by freemangordon** [comment]
maybe we can try http://repository.maemo.org/pool/fremantle/free/o/osso-applet-screencalibration/

**Comment by parazyd** [comment]
@freemangordon This still produces evdev calibration values, same like xinput-calibrator.

**Comment by IMbackK** [comment]
well libinput gets its calibration values from udev and udev gets its cal values from its rules or the kernel dts. for capactive screens this is the correct behavior, as each device needs the exact same calibration.

only the n900 needs on-line calibration.

besides the point here is that for many input devices libinput works better or only works with them, the fact that atm we callibrate our ts devices of the phone screens via x11's xorg.conf is no reason to force remove libinput as we can simply direct x11 to use its evdev driver for those devices. otoh if i plug in a external ps5 gamepad with a integrated touch pad or whatever with mainline  calibration it wont work on leste because libinput is unavailable.. for no reason what so ever.

**Pull request merged**
